name: Mirror Images to GHCR

on:
  workflow_dispatch:
    inputs:
      images:
        description: 'List of images to mirror, separated by commas (e.g., studio:v1.0.0,worker:v1.2.3,api:latest)'
        required: true
        type: string

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Mirror Images
        run: |
          images_list=$(echo "${{ inputs.images }}" | tr ',' '\n')
          for image in $images_list; do
            if [[ "$image" == *"/"* ]]; then
              image_repository=$(echo "$image" | cut -d '/' -f 1)/
              image_name=$(echo "$image" | cut -d '/' -f 2 | cut -d ':' -f 1)
            else
              image_repository=""
              image_name=$(echo "$image" | cut -d ':' -f 1)
            fi
            image_tag=$(echo "$image" | cut -d ':' -f 2)
            echo "${image_repository}, ${image_name}, ${image_tag}........."
            docker pull docker.io/${image_repository}${image_name}:${image_tag}
            docker tag docker.io/${image_repository}${image_name}:${image_tag} ghcr.io/nuersir/supabase/${image_name}:${image_tag}
            docker push ghcr.io/nuersir/supabase/${image_name}:${image_tag}
          done
